# https://github.com/actions/checkout
# https://docs.github.com/actions/using-workflows

name: 'GitHub Continuous Integration'

on: [push, pull_request]

jobs:
  macos:
    runs-on: macos-latest
    steps:
      - uses: actions/checkout@v2
      - name: Install dependencies
        run: brew install pkg-config sdl2
      - name: Build & Test
        run: make all test

  ubuntu:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Install dependencies
        run: sudo apt-get install pkg-config libsdl2-dev
      - name: Build & Test
        run: make all test
